### ISSUE TITLE
Update SDK to 21.08

### ISSUE THREAD

**Issue by renatobellotti** [flathub/io.atom.Atom#105]
According to the flatpak documentation (https://docs.flatpak.org/en/latest/available-runtimes.html), there is a newer version of the SDK.

**Comment by codingepaduli** [comment]
Please, I'm waiting the same..

**Comment by darkdragon-001** [comment]
Looks like there are some build errors which need to be resolved #106

**Comment by cpba** [comment]
Fixed in #134
