### ISSUE TITLE
Metadata shows wrong version

### ISSUE THREAD

**Issue by jonathancross** [flathub/io.atom.Atom#107]
Current Flatpak is way behind current release of v1.58.0, would be nice to get it updated.

**Comment by cpba** [comment]
@jonathancross What do you mean? This flatpak has been at 1.58.0 for several months: https://github.com/flathub/io.atom.Atom/commit/15bc30ffc36663ce96e3be514a8492c6764adf0d

What version do you have?

**Comment by cpba** [comment]
Yes the appdata file is wrong: https://github.com/flathub/io.atom.Atom/blob/master/io.atom.Atom.appdata.xml#L22

I'll fix it manually
