### ISSUE TITLE
Menus using wrong colors/theme and ugly fonts

### ISSUE THREAD

**Issue by devhen** [flathub/io.atom.Atom#11]
Does anyone know why this flatpak uses the wrong colors and theme for its menus while other electron-based flatpaks on flathub like Slack don't have that problem? The fonts in the menus are also a bit jagged and poorly.

Atom:
![Atom](https://i.imgur.com/m6WU59g.png)

Slack:
![Slack](https://i.imgur.com/dvuFKA6.png)

Visual Studio Code (com.visualstudio.code.oss) from flathub seems to have this same problem. I wonder if there is an easy fix for this.

I am on Fedora 28 by the way.

**Comment by TingPing** [comment]
This should be fixed once Atom uses Electron 2.0. Not sure an ETA for that exists or not.

**Comment by devhen** [comment]
Thanks.

It looks like the upgrade to Electron 2.0 will be happen very soon, its mentioned in the changelog for Atom 1.28.0-beta0.

https://atom.io/releases

**Comment by TingPing** [comment]
Cool, I built the beta just to test and can confirm menus are correct now.

**Comment by devhen** [comment]
It looks like Visual Studio Code will be moving to Electron 2.0 soon as well. :thumbsup:

https://github.com/Microsoft/vscode/issues/45542#issuecomment-395816229

**Comment by TingPing** [comment]
Fixed by https://github.com/flathub/io.atom.Atom/commit/713f045a7ed3fcb78c9ecefb4b54861964da23c1
