### ISSUE TITLE
Using external libraries [Fedora 28]

### ISSUE THREAD

**Issue by koenigjaeger** [flathub/io.atom.Atom#12]
OS: Fedora 28

Currently it doesn't seem possible to use certain extensions for atom (i.e. hydrogen, Platformio Ide Terminal, etc), since they can't see any of the (in this case) python3 libraries that are installed by the OS's package manager. Is this just an issue with allowing atom more access to certain paths? (seeing as the rpm package from their website works (atom.io).)

**Comment by TingPing** [comment]
Flatpaks are sandboxed, there are some ways to call cli tools on the host but there is no way to sanely import libraries from the host.

**Comment by TingPing** [comment]
@nsrosenqvist It is impossible to pull the host into the sandbox and expect anything to work, you can however do the reverse and use `flatpak-spawn --host foo` to run tools on the host.

**Comment by TingPing** [comment]
@nsrosenqvist A combination of extensions (shared between all IDE packages here) and `flatpak-spawn --host` probably.

**Comment by lentzi90** [comment]
Is there a timeline for when this will be fixed? How/where can I help? I am especially interested in getting the IDE package for python working with pyls.

**Comment by koenigjaeger** [comment]
My main issue currently is to see juno for Julia working. Although how are other IDE's working? ie. Pycharm. Do they just remove all sandboxing features of flatpak to work with system packages?

**Comment by rugk** [comment]
BTW same issue for many tools: Basically anything that opens a build tool/compiler or so…
Even simple things [like shellcheck](https://github.com/AtomLinter/linter-shellcheck/issues/115) are affected.
[Here is another suggested workaround.](https://unix.stackexchange.com/questions/412869/how-to-allow-gui-application-in-flatpak-to-run-cli-tool/422438#422438)

Seeing `flatpak-spawn --host foo` here, will this immediately start the tool in the flatpak? For some tools  that may be possible, but others need to return/STDOUT some stuff to Atom back. For shellcheck, e.g. it would be great if that spawn command could just expose this one library/program I need into the flatpak, so it is allowed to start it (inside the flatpak, possibly).

**Comment by rugk** [comment]
BTW, thanks to [some Silverblue users](https://discussion.fedoraproject.org/t/goals-for-fedora-silverblue-30/773/25?u=rugk), I was able to configure Atom to properly run shellcheck. As that may be useful in many cases, I post it here.

So first, I _do not need_ the extra "talk to flatpak" permission. That is only required when you want to run commands actually _on the host_ (`flatpak-spawn --host`) and is thus a very **dangerous** permission. In my case, the tool to run was totally self-contained, so I could actually increase security and run it in an even stronger sandbox than what Atom has.

The only problem was the configuration GUI of the Atom package that just allowed me to add a single command (parameters did not work), so what you have to do then is to create a simple wrapper script such as this one:
```sh
#!/bin/sh
flatpak-spawn --sandbox --no-network --clear-env shellcheck "$@"
```

(It uses the strongest sandbox options I could quickly find, but still has access to the current dir it was started from AFAIK.)

Then you have to save it in a path _accessible to the flatpak_. Note that the the usual `/usr/lib/bin` or so is  **not** possible, as it is not mounted in the flatpak. Instead, your home dir or so may be possible. (I know, a little ugly…)
Finally you just configure Atom to use this script, and it works. :smiley: And remember, it has an even stronger sandbox… :blush:

**Comment by rugk** [comment]
Okay, no, I actually missed to save the file :man_facepalming:, actually, it seems to fail with shellcheck even if I do not add `--sandbox`, which should make the files readable, at least.

In any case, however, the  `--host` version works:
```sh
#!/bin/sh
# --sandbox and --no-network do not work
flatpak-spawn --host shellcheck "$@"
```

**Comment by cpba** [comment]
> Note that the the usual /usr/lib/bin or so is not possible, as it is not mounted in the flatpak.

@rugk In case this helps you, know that it is indeed mounted. As this manifest sets `--filesystem=host`, you'll find your host's `/usr` under `/var/run/host/usr`

**Comment by rugk** [comment]
Ah okay, thanks. Then I can put the file in a better location. 😃 

(AFAIK `/var/run/host/usr` is just not in the `$PATH` by default, so you need to pass the full path then, but that's okay.)

**Comment by TingPing** [comment]
I'm just closing this. I think the situation is discussed and a workaround provided.

**Comment by rugk** [comment]
FYI same solution for enabling GPG signing within Atom:
```sh
#!/bin/sh
# if this runs in a flatpak, spawn a command on the host instead
if [ "$FLATPAK_ID" != "" ]; then
	# --sandbox, --clear-env and --no-network do not work
	flatpak-spawn --host gpg2 "$@"
else
	gpg2 "$@"
fi
```

(potentially need to replace `gpg2` with `gpg` depending on your used version)

Afterwards set this as your sign command in `.gitconfig`:
```
git config  --global gpg.program "/path/to/script"
```

**Comment by rugk** [comment]
BTW also created a repo with these scripts and more detailed instructions: https://github.com/rugk/atom-flatpak-wrapper

**Comment by koenigjaeger** [comment]
I have been trying to give access to /usr/bin/julia with no luck. Has anyone tried to get juno working? or hydrogen?

**Comment by koenigjaeger** [comment]
@rugk are you just running...

```
#!/bin/sh
# --sandbox and --no-network do not work
flatpak-spawn --host --clear-env shellcheck "$@"
```
In an atom-based terminal?

**Comment by rugk** [comment]
> I have been trying to give access to /usr/bin/julia with no luck.

Note that if the flatpak has `host` access, you do not need any workarounds, and you can just use the path `/var/run/host/usr/local/bin/julia` inside of the flatpak, so just enter/use that, whereever it is requested.

> In an atom-based terminal?

No, needs to be in a shell script. See https://github.com/rugk/atom-flatpak-wrapper

**Comment by rugk** [comment]
Also added taht info in https://github.com/rugk/atom-flatpak-wrapper/pull/2 BTW.

**Comment by fedelibre** [comment]
> > I have been trying to give access to /usr/bin/julia with no luck.
> 
> Note that if the flatpak has `host` access, you do not need any workarounds, and you can just use the path `/var/run/host/usr/local/bin/julia` inside of the flatpak, so just enter/use that, whereever it is requested.

@rugk I'm building a [flatpak of an editor](https://github.com/fedelibre/org.frescobaldi.Frescobaldi/tree/v3.0.0) which requires access to a CLI application (I've bundled it initially but I want to remove the bundle).
The editor can add as many versions of this CLI application as you have installed. I see that I can easily add the application if it's installed in my home directory, but not if it's installed in /usr. The manifest gives access to the host filesystem.

I'd be Ok with the editor being able to load only the binaries in my home. But I'm curious to know why the binaries in /usr are not used.

Forgot to say: **I'm using the actual path in my host.** `~/.local/bin/lilypond` works while `/usr/bin/lilypond` doesn't.
If I prepend /var/run to /usr/bin/... the application is found but not the needed scheme library:

```
/var/run/host/usr/bin/lilypond: error while loading shared libraries: libguile.so.17: cannot open shared object file: No such file or directory
```

**Comment by fedelibre** [comment]
I read [here](https://github.com/flatpak/flatpak/issues/2538#issuecomment-456005817) that /home and /opt are available when filesystem=host is set. While /usr and /etc must be in /run/host.
That's fine for my case.

**Comment by TingPing** [comment]
Just because the directory exist doesn't mean you can use it. The sandbox has a completely different ABI from the host so when anything works its up to pure dumb luck.

**Comment by cpba** [comment]
@fedelibre What you want to do is possible, but you're going at it the wrong way. The binaries you are trying to run were built for the host and there's no guarantee that they'll run on the sandbox.

As discussed earlier in this issue, you must use `flatpak-spawn --host` in order to run the binaries outside the sandbox.

**However**, running host binaries defeats the whole purpose of flatpak and exposes you to all the age old problems inherent in traditional software distribution methods. Do not do it unless strictly necessary, and even then keep in mind it's generally a very bad idea.

**Comment by fedelibre** [comment]
Thanks for your feedback, I'll keep this in mind.

Actually, I want to bundle the stable version of the CLI application (LilyPond). But being able to run also the development version from the host is very convenient. LilyPond has a very slow stable release cycle; the last stable is 5 year old. Many LilyPond users are using the development version since years; the last one is a sort of beta release.

This is obviously a LilyPond problem but should be taken into account when building the flatpak of Frescobaldi editor.
