### ISSUE TITLE
git integration feature always asks for ssh passphrase

### ISSUE THREAD

**Issue by cpba** [flathub/io.atom.Atom#13]
When trying to push into a git repository using ssh, atom asks for the passphrase every time a push is attempted.

This contrasts with the rpm version, where the passphrase is only requested once.

**Comment by FlorianLudwig** [comment]
The reason for this is that your ssh-agent is not accessible from within the sandboxed flatpak.

You can work around this by explicitly allowing the access by starting atom via:
```
flatpak run --filesystem=$SSH_AUTH_SOCK io.atom.Atom
```

**Comment by cpba** [comment]
Thank you.

Could you shed some light on why this works? I mistakenly assumed it would already work with the manifest setting `--filesystem=host`.

**Comment by FlorianLudwig** [comment]
```
$ echo $SSH_AUTH_SOCK
/run/user/1000/keyring/ssh
```
This path can't be mapped into a flatpak container directly. From the [docs](http://docs.flatpak.org/en/latest/sandbox-permissions.html):


As mentioned above the host option does not actually provide complete access to the host filesystem. The main rules are:

> 
> * These directories are blacklisted: /lib, /lib32, /lib64, /bin, /sbin, /usr, /boot, /root, /tmp, /etc, /app, /run, /proc, /sys, /dev, /var
> * Exceptions from the blacklist: /run/media
> * These directories are mounted under /var/run/host: /etc, /usr

**Comment by nedrichards** [comment]
And just to give a little more context, adding this permission for everyone requires the vast majority of users to have at least [flatpak 0.10.3](https://github.com/flatpak/flatpak/releases/tag/0.10.3) (releases before then fail when they see unknown permissions). We only have flathub version stats from Flatpak 0.11.3 onwards, and that or newer is currently at 60% of usage. I'd love to see that get higher before we turn this on by default. (we believe the main 'offender' is CentOS/RHEL which are on 0.8.8 fwiw.)

**Comment by cpba** [comment]
@matthewwardrop Thank you for contributing, that's another one down.
