### ISSUE TITLE
Unable to access atom or apm executables from command line

### ISSUE THREAD

**Issue by fredrikekelund** [flathub/io.atom.Atom#20]
I am new to the Flathub ecosystem, but wanted to dip my toes in the water by installing Atom now that Flatpak 1.0 has been released (I'm running Fedora 28). A limitation that I noticed straight away was that I couldn't access the `atom` and `apm` executables from my terminal. Is this something that could be fixed in this package, or is it a technical limitation of the Flatpak sandboxing?

**Comment by TingPing** [comment]
`flatpak run --command=apm io.atom.Atom ...`

**Comment by TingPing** [comment]
You can make aliases in your shell for `atom` and `apm` if you want.

**Comment by fredrikekelund** [comment]
Thanks! Would it be possible to distribute command line aliases with the Flatpak package? I'm not familiar with the Flatpak convention here, but seeing as everything else worked as I expected out of the box, this seems like it could confuse others as well.

**Comment by TingPing** [comment]
No, the name is part of the design. Two packages never conflict and it doesn't override other commands.

There have been thoughts on how to make it nicer but it is what is is atm.
