### ISSUE TITLE
CLI path bug with Atom 1.30.0

### ISSUE THREAD

**Issue by ThomasLandauer** [flathub/io.atom.Atom#21]
See https://github.com/atom/ide-php/issues/127 : It never worked with flathub's Atom. However, when I installed the `.deb` package from their website, it worked right away.

**Comment by TingPing** [comment]
Yes Atom runs in a sandbox, so host things can't work.

**Comment by TingPing** [comment]
No because it works fine. The issue is more nuanced than that but its been discussed a dozen times on this repo. This just needs to be documented and more things packaged.

**Comment by ThomasLandauer** [comment]
Just for reference, this is the issue you're referring to, right? https://github.com/flathub/io.atom.Atom/issues/12
