### ISSUE TITLE
Using SDK reference as Runtime

### ISSUE THREAD

**Issue by tingvarsson** [flathub/io.atom.Atom#22]
Noticed when I did a summary of Runtimes used on my system.

All other apps still on 1.6 are using the following ref as platform:

`org.freedesktop.Platform/x86_64/1.6
`

https://github.com/flathub/io.atom.Atom/blob/81e563be5204d819f2593a97a3bd63f4fcaf015a/io.atom.Atom.json#L6

I presume the impact is minor since it still works, but could be good to clean up.

PS. Do you know what guidelines/gains there are regarding uplifting to newer freedesktop runtime (18.08)? 60% of my installed applications have moved over to 18.08 in favor of 1.6.
Otherwise that is an improvement suggestion as well.

**Comment by TingPing** [comment]
It is an IDE so it finds many of the tools in the Sdk useful such as `git`.

`18.08` has newer versions and is just better maintained and supported.

**Comment by tingvarsson** [comment]
Wow, great response time. And thanks for the answer, makes sense. :)
