### ISSUE TITLE
apm uses non-flatpak user config folder

### ISSUE THREAD

**Issue by ramesh45345** [flathub/io.atom.Atom#3]
This may be more of a question than an issue.

I routinely use the `apm` command to install extensions for Atom. It is my understanding that the command to run `apm` using the flatpak contained version is `flatpak run --command=apm io.atom.Atom <parameters>`, where `<parameters>` are the commands I want to issue to apm, such as `list`, or `install`. When I run this command though, it uses my home folder's atom profile: `/home/user/.atom`, where `user` is the name of the current user. Note that I do not have Atom installed natively (through an rpm or deb), I have only installed Atom through flatpak.

When I run `flatpak run --command=apm io.atom.Atom list`, the command yields the following output (the language plugin output has been trimmed):
```
...

Community Packages (0) /home/user/.atom/packages
└── (empty)
```

I understand that the flatpak user config folder is located at `/home/user/.var/app/io.atom.Atom/data`. The above folder in the output is my actual user's home folder, which is where a native install of atom might place its files. This means that if I use apm with this command, Atom will not see the installed extensions, since they won't exist in the `/home/user/.var/app/io.atom.Atom/data` path.

What would be necessary to cause apm to use the flatpak packages folder found in `/home/user/.var/app/io.atom.Atom/data`, as opposed to `/home/user/.atom`?

**Comment by TingPing** [comment]
It probably has an env var to change it.
