### ISSUE TITLE
Restriction of filesystem breaks multiple packages, including terminal emulators and linters

### ISSUE THREAD

**Issue by jon2kx** [flathub/io.atom.Atom#39]
https://github.com/platformio/platformio-atom-ide-terminal/issues/664

Essentially, for terminal emulators, required directories have incorrect permissions, and are not accessible at all. 

Linters are found to be missing in path. 

This affects every terminal emulator available. 

Please consider modifying your manifest to allow read/execute in appropriate locales. I don't think this application is an ideal scenario for sandboxing, because it limits the functionality.

**Comment by TingPing** [comment]
It has the broadest filesystem mounts it can. You simply can't run host executables directly you must use the `flatpak-spawn --host foo` tool.
