### ISSUE TITLE
Remove dangerous flatpak bus talk permission

### ISSUE THREAD

**Issue by rugk** [flathub/io.atom.Atom#43]
This flatpak does have the talk permission for `org.freedesktop.Flatpak` (Session Bus Policy).

That is a very **dangerous** permission, because it allows the app iside the flatpak to run `flatpak-spawn --host` to execute arbitrary commands outside of the flatpak on the host system, i.e. it allows sandbox escape.

I wonder, why you think this permission is necessary.

**Comment by TingPing** [comment]
Its a dev tool, developers like flexibility, the permissions otherwise are extremely lax anyway (host fs).
