### ISSUE TITLE
Update to v1.36

### ISSUE THREAD

**Issue by rugk** [flathub/io.atom.Atom#46]
v1.36 has been released a few days ago, already, but not yet updated as it seems. See https://blog.atom.io/2019/04/09/atom-1-36.html

**Comment by cpba** [comment]
I try to update within a day or two, but I have been busy this week.

If you want to open a pull request and do the testing I'll make sure to merge it. Otherwise I'll try to update it tomorrow when I have some time.

**Comment by rugk** [comment]
Actually, i always thought in the past that this update process is automated on flathub… :smile:

**Comment by cpba** [comment]
Fixed in #47
