### ISSUE TITLE
gtk-dark-theme doesn’t work

### ISSUE THREAD

**Issue by ai** [flathub/io.atom.Atom#53]
Seems like [gtk-dark-theme](https://atom.io/packages/gtk-dark-theme) is the only way to use dark window decorator for Atom. And this plugin doesn’t work in Atom from Flatpak (but works correctly in `atom.rpm`).

Maybe policies don’t allow to call `xprop`? Here is how extension [change the theme](https://atom.io/packages/gtk-dark-theme).

Maybe somebody knows a different way to force Flatpak’s Atom to use the dark theme (if system uses the light theme)?

Versions:

```
➜ flatpak run io.atom.Atom --version
Atom    : 1.38.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

Fedora 30 with Adwaita

**Comment by TingPing** [comment]
`xprop` just isn't in the package. Somebody could add it I suppose.

**Comment by ai** [comment]
@TingPing how we can add it? Maybe we can make PR?

**Comment by cpba** [comment]
Sure, make a pull request.

Dark themes are oddly very popular lately, so as long as it's reasonably
clean I can't think of a reason not to merge it.

**Comment by ai** [comment]
@cpba I do not know how to do it. Maybe there is any help about adding binaries to flatpak?

**Comment by TingPing** [comment]
https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L92-L101

**Comment by ai** [comment]
@TingPing thanks.

Done https://github.com/flathub/io.atom.Atom/pull/54
