### ISSUE TITLE
No connection to finding go tool

### ISSUE THREAD

**Issue by Jacalz** [flathub/io.atom.Atom#64]
When using the `go-plus` extension with the flatpak version the extension fails to find the go tool (in other words the installed golang package) on linux. I guess it is because the sandbox doesn't let it, could this please be fixed?

**Comment by Jacalz** [comment]
I’m not that experienced when it comes to Flatpak and especially not extensions. I basically just use the Flatpaks. I mean go as in the language created by Google. golang.org

**Comment by cpba** [comment]
I don't know how to proceed with this, on one hand it isn't feasible to bundle every dependency any possible extension may need. But on the other hand we don't have an user friendly way for users to get what they need into the extension point.

Hopefully @TingPing can chime in on this when he has time

**Comment by Jacalz** [comment]
I don’t think packaging go is a good idea. It would be better to just make some kind of bridge if it’s possible.

**Comment by Jacalz** [comment]
I am not using Atom anymore. Will close.
