### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by codingepaduli** [flathub/io.atom.Atom#65]
Update runtime to 19.08, please.

**Comment by cpba** [comment]
@codingepaduli could you please test #66 ?

It's this build:
https://flathub.org/builds/#/builders/32/builds/9105
Quick way to install it:
`flatpak install --user https://dl.flathub.org/build-repo/8620/io.atom.Atom.flatpakref`

**Comment by fuzzysloth** [comment]
For AMD Ryzen 5 owners this would also fix the same issue as in org.signal.Signal:
https://github.com/flathub/org.signal.Signal/issues/99

**Comment by cpba** [comment]
This was done last year but I forgot to close the issue.
