### ISSUE TITLE
Make Atom available for AArch64 (ARM) architecture

### ISSUE THREAD

**Issue by cobratbq** [flathub/io.atom.Atom#72]
With the rising popularity of ARM-based notebooks as light-weight notebooks, it would be nice to have Atom as flatpak available. With the popularity of Pinebook Pro, and Manjaro Linux ARM as linux distribution, it becomes feasible to install an Atom flatpak on an ARM 64-bit system. (However it is not currently available.)

**Comment by cpba** [comment]
Does upstream atom provide aarch64 packages?

**Comment by cobratbq** [comment]
@cpba you make a good point. I wrongly assumd that if Visual Studio Code OSS (open source build) has an AArch64 variant, that Atom would surely have one too. I'll check with the atom.io people first ;-)
