### ISSUE TITLE
Atom launches twice

### ISSUE THREAD

**Issue by sgebauer** [flathub/io.atom.Atom#93]
Since the last update, atom always launches two instances.

To reproduce, simply run `flatpak run io.atom.Atom`. A few seconds after atom
has started, a second atom window will open. This second window...

* seems to be a separate instance (Ctrl+Q in one window will not close the other one)
* always uses default settings and shows the welcome screen
* has `$HOME/.var/app/io.atom.Atom/data/compile-cache` as the project folder

This does not happen if i revert to the last commit (`flatpak update --commit=7302bb14a117f156ef58ade8a7ac1cb51b6133cd8e9c672c223e24651c4de1ff io.atom.Atom`).

(Flatpak version is 1.10.1 from Debian buster-backports)

**Comment by cpba** [comment]
I am unable to reproduce this.

However, it could be related to me sidestepping the usual launch shell script in order to upgrade to upstream `zypak`, if you're sure this isn't caused by something else I'll just revert it and try a cleaner workaround the next time.

**Comment by sgebauer** [comment]
I can reproduce this in a fresh Debian 10 VM, so it's not caused by any part of my specific setup.

The only additional condition seems to be that atom's restored state needs to have a project folder open. Starting from a fresh install, you need to do the following:
* Start atom
* Open a project folder
* Quit atom
* Start it again

**Comment by cpba** [comment]
@sgebauer just to make sure before I merge, could you please test the build [here](https://github.com/flathub/io.atom.Atom/pull/94#issuecomment-778431268) to see whether it fixes your issue?

**Comment by sgebauer** [comment]
Yes, i can't reproduce it any more with the linked build.
